config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'
  get '/auth/spotify/callback', to: 'sessions#create'
  post '/comment_add', to: 'comments#create'
  post '/playlist_add', to: 'comments#makePlaylist'
  get '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, :moods, :comments
  resources :sessions, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :mood
  belongs_to :user
end

app/models/mood.rb
class Mood < ActiveRecord::Base
  validates :title, presence: true

  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: true
  validates :credentials, presence: true

  has_many :moods
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :spotify_search, :playlist_create, :playlist_add

  def initUser
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    @hash = spotify_user.to_hash
  end

  def updateUser
    spotify_user = RSpotify::User.new(session[:spotify_user])
  end

  def spotify_search(track_name, artist_name)
    track_name = track_name.gsub(" ", "+")
    artist_name = artist_name.gsub(" ", "+")
    response = HTTParty.get("https://api.spotify.com/v1/search?q=#{track_name}+#{artist_name}&type=track,artist")
    uri = response['tracks']['items'][0]['uri']
    uri.slice!("spotify:track:")
    uri
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find_by(id: params[:id])
  end

  def create
   comment = params['comment']
   user_id = User.find_by(email: params[:user_email]).id
   mood_id = params[:mood_id]
   uri = spotify_search(comment['track_name'], comment['artist_name'])
   Comment.create(content: comment['content'],
                artist_name: comment['artist_name'],
                track_name: comment['track_name'],
                created_at: Time.now,
                updated_at: Time.now,
                user_id: user_id,
                mood_id: mood_id,
                uri: uri)
   redirect_to :back
  end

  def update
    @user = User.find_by(id: params[:id])
    Comment.find_by(id: params[:id]).update(comment_params)
    redirect_to ('/users')
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :mood_id)
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
  end

  def destroy
    Comment.destroy(params['id'])
    redirect_to :back
  end

   def makePlaylist
    playlist_info = params['playlist']
    mood_id = params[:mood_id]
    spotify_user = updateUser
    playlist = spotify_user.create_playlist!(playlist_info['playlist_name'])

    commentList = Comment.where(mood_id: mood_id)
    trackList = []
    commentList.each do |comment|
      uri = comment.uri.gsub("spotify:track:", "")
      track = RSpotify::Track.find(uri)
      trackList.push(track)
    end
    trackList
    playlist.add_tracks!(trackList)
    redirect_to :back
  end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController

  def index
    @moods = Mood.where.not(user_id: "#{User.find_by(email: session[:spotify_user]["email"]).id}")
  end

  def show
    @mood = Mood.find_by(id: params[:id])
    @comments = Mood.find_by(id: params[:id]).comments
    @allUris = String.new
    @comments.reverse_each do |comment|
      @allUris += "#{comment.uri.gsub("spotify:track:", "")},"
    end
    @allUris.chop!
    @moodTitle = @mood['title']
  end

  def create
    #add mood to db
    mood = params['mood']
    Mood.create( title: mood['title'],
                 created_at: Time.now,
                 updated_at: Time.now,
                 user_id: params[:user_id])
    redirect_to :back
  end

  def update
    mood = params['mood']
    Mood.create(content: mood['content'],
                 title: mood['title'],
                 created_at: Time.now,
                 updated_at: Time.now,
                 user_id: mood['user_id'])
  end
  def delete

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @hash = initUser
    emailCheck = User.find_by(email: @hash['email'])

    if emailCheck == nil
      User.create(display_name: @hash['display_name'],
                  email: @hash['email'],
                  country: @hash['country'],
                  followers: @hash['followers'],
                  images: @hash['images[0].url'],
                  credentials: @hash['credentials'],
                  spotify_id: @hash['id'],
                  created_at: Time.now)
    end
    session[:spotify_user] = @hash

    redirect_to "/users/#{User.find_by(email: @hash['email']).id}", :notice => "Signed in!"
  end

  def destroy
    session[:spotify_user] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    @userMoods = Mood.where(user_id: @user["id"])
    # @image = RSpotify::User.find('justinjohnso').images[0]['url']
    @user_comments = User.find_by(id: params[:id]).comments
    # @moods = Mood.find_by(title: params[:title]).comments.where("user_id = #{params[:id]}")
    # @mood_comments = @moods.map do |mood|
    #   mood
    # end
    @all_comments = @user_comments.map do |comment|
      comment
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spotify_helper.rb
module SpotifyHelper
  def initUser
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    @hash = spotify_user.to_hash
  end
  def updateUser
    spotify_user = RSpotify::User.new(@hash)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_dashboardnav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/moods">Mood List</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
<!--         <li><a href="#">Random!</a></li> -->
        <!-- <li class="active"><a href="#">Dashboard <span class="sr-only">(current)</span></a></li> -->

        <li>
          <%= link_to "Logout", session_path, method: :delete %>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_footer.html.erb
<footer>
  <a href="" title="" data-toggle="modal" data-target="#aboutModal">About</a>

  <div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h3 class="modal-title" id="myModalLabel">About:</h3>
        </div>
        <div class="modal-body">
          <p>This app is all about community.</p>
          <p>We believe that music is strongly connected with whatever mood you're in. That's why we thought it'd be a good idea to build a community around sharing songs specific to certain moods/feelings. Here we've created a space where members can share their tastes / be influenced by others.</p>
          <p>We hope you enjoy contributing to our community and the new tunes you come across!</p>
        </div>
      </div>
    </div>
  </div>

  <a href="" title="" data-toggle="modal" data-target="#contactModal">Contact</a>

  <div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h3 class="modal-title" id="myModalLabel">The Team:</h3>
        </div>
        <div class="modal-body">
          <h4>Take a gander at our GitHubs</h4>
          <p><a href="https://github.com/justinjohnso">Justin Johnson</a></p>
          <p><a href="https://github.com/gbasgaard">Glenn Basgaard</a></p>
          <p><a href="https://github.com/MBSilvaR">Marcela Silva</a></p>
          <p><a href="https://github.com/danielnormandia">Daniel Normandia</a></p>
          <p><a href="https://github.com/redfolgersGA">Emmanuel Paulino</a></p>
        </div>
      </div>
    </div>
  </div>
  <p>&copy; 2016 Boolean</p>
</footer>

app/views/application/_moodsnav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <li><a class="navbar-brand" href="/users/<%="#{User.find_by(email: session[:spotify_user]['email']).id}"%>">Dashboard</a></li>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/application/_search.html.erb
<%= form_tag(@moods, method: "get") do %>
<%= label_tag(:title, "Search a Mood") %>
<%= text_field_tag(:title) %>
<%= submit_tag("Search") %>
<% end %>

app/views/comments/edit.html.erb
<div class="form-styling">
  <%= form_for @comment do |f| %>
    <%= f.label :content %>:
    <%= f.text_field :content %><br />

    <%= f.submit %>

  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppArchitecture</title>
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <main class="site-content">
      <%= yield %>
    </main>
    <%= render "footer" %>
  </body>
</html>

app/views/moods/index.html.erb
<%= render "moodsnav" %>

<h1 id="moods-header"> How am I feeling? </h1>

<% @moods.each do |mood| %>
<div>
  <li id="moods">
  <%= link_to mood['title'], mood_path(mood) %></li>
</div>
<% end %>
<h3>Add your mood!</h3>
<%= form_for :mood, method: 'post', url: "/moods" do |f| %>
  <%= label(:mood, :title) %><br>
  <%= f.text_field :title %><br>
  <%= hidden_field_tag :user_id, "#{User.find_by(email: session[:spotify_user]["email"]).id}" %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/moods/new.html.erb
<%= form_for :mood, method: 'post', url: {action: 'create'} do |f| %>
  <%= label(:mood, :title) %><br>
  <%= f.text_field :title %><br>
  <br>
  <%= f.submit "Share your mood" %>
<% end %>

app/views/moods/show.html.erb
<!-- This is the dashboard -->
<div class="container moods-show">

  <h1 class="mood-title" data-mood="<%= @mood['title'] %>"><%= @mood['title'] %></h1>

  <br><br>

  <div class="row">

    <div class="comments-wrapper col-md-8">
      <% @comments.reverse_each do |comment| %>
      <div class="comment" data-uri="<%= spotify_search(comment['track_name'], comment['artist_name']) %>">
        <span class="legend"><%= comment['track_name'] %></span> <span class="key">by</span><span class="legend"><%= comment['artist_name'] %></span> <br>
        <span class="key"><%= comment['content'] %></span> <br><br>
      </div>
      <% end %>

      <h3>Add a song to the playlist:</h3>
      <%= form_for :comment, html: {class: "form-styling"}, method: 'post', url: "/comment_add" do |f| %>
      <%= label(:comment, :track_name) %><br>
      <%= f.text_field :track_name %><br>
      <%= label(:comment, :artist_name) %><br>
      <%= f.text_field :artist_name %><br>
      <%= label(:comment, :comment) %><br>
      <%= f.text_area :content %><br>
      <%= hidden_field_tag :user_email, session['spotify_user']['email'] %>
      <%= hidden_field_tag :mood_id, @mood['id'] %>
      <br>
      <%= f.submit "Submit Comment" %>
      <% end %>
    </div>

    <div class="spotify-list-wrapper col-md-4">
      <div class="affix">

         <div class="add-to-user-playlist">
          <%= form_for :playlist, html: {class: "form-styling"}, method: 'post', url: "/playlist_add" do |f| %>
          <%= label(:playlist, "Name Your Playlist") %><br>
          <%= f.text_field :playlist_name %><br>
          <%= hidden_field_tag :mood_id, @mood['id'] %>
          <br>
          <%= f.submit "Add to your Spotify" %>
          <% end %>
          <br><br>
        </div>

        <div class="spotify-embed-list">
          <iframe class="spotify-embed-many" src="https://embed.spotify.com/?uri=spotify:trackset:<%= @moodTitle %>:<%= @allUris %>" frameborder="0" allowtransparency="true" width="300" height="300"></iframe>
        </div>

      </div>
    </div>
  </div>


</div>

app/views/users/index.html.erb
<div id="spotify_button">
  <%= link_to '<i class="fa fa-spotify fa-5x" aria-hidden="true"></i><br>Log In'.html_safe, '/auth/spotify' %>
</div>

<%= video_tag "background.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>

app/views/users/show.html.erb
<%= render "dashboardnav" %>
<div class="container">

  <div id="user-info" class="col-xs-7 col-md-4 img-rounded">
    <p>Name: <%= @user['display_name'] %></p>
    <% if @user['spotify_id'] != nil %>
      <p>Username: <%= @user['spotify_id'] %></p>
    <% end %>
    <p>Email: <%= @user['email'] %></p>
    <p>Country: <%= @user['country'] %></p>
  </div>

  <div class="row"></div>
  <br><br>

  <div class="col-md-12 text-center">
    <h1>My Moods</h1>
    <div class='suggestions'>
      <% @userMoods.each do |mood| %>
      <span class="legend">Mood: </span><span class="key"><%= mood['title'] %> |</span>
      <%= link_to "View Mood Thread", "/moods/#{mood.id}" %><br><hr>
    <% end %>
    </div>
  </div>

  <div class="col-md-12 text-center">
    <h1>My Suggestions</h1>
    <div class='suggestions'>
      <% @all_comments.each do |comment| %>
      <span class="legend">Comment: </span><span class="key"><%= comment['content'] %> |</span>
      <span class="legend">Artist: </span><span class="key"><%= comment['artist_name'] %> |</span>
      <span class="legend">Track: </span><span class="key"><%= comment['track_name'] %></span><br>
      <a href='/comments/<%= comment["id"] %>/edit'>Edit this comment!</a><br>
      <%= button_to 'Remove this comment', comment, method: :delete, class: "btn btn-danger" %><br><hr>
    <% end %>
    </div>
  </div>


</div>